// <auto-generated />
using System;
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Entities.Migrations
{
    [DbContext(typeof(ContactsDbContext))]
    [Migration("20251128115007_UpdatePersonNameColumn")]
    partial class UpdatePersonNameColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Country", b =>
                {
                    b.Property<Guid>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CountryName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CountryId");

                    b.ToTable("Countries", (string)null);

                    b.HasData(
                        new
                        {
                            CountryId = new Guid("bc5c0290-49fb-423d-9440-007db6ac1363"),
                            CountryName = "USA"
                        },
                        new
                        {
                            CountryId = new Guid("7a536480-94b8-40ea-991d-6cac7ac32a86"),
                            CountryName = "UK"
                        },
                        new
                        {
                            CountryId = new Guid("ae6f4b3a-ec46-4e34-99e3-64a0f0d2174b"),
                            CountryName = "Canada"
                        },
                        new
                        {
                            CountryId = new Guid("8efba64c-38da-4956-8733-dbef6ac860b2"),
                            CountryName = "Australia"
                        },
                        new
                        {
                            CountryId = new Guid("e7d45e4a-be35-4955-9e3a-53e3829df119"),
                            CountryName = "Spain"
                        });
                });

            modelBuilder.Entity("Entities.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PersonName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("RecieveNewsletter")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Persons", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("8ba16644-a00a-4722-8e76-336432127180"),
                            Address = "135 abied st",
                            BirthDate = new DateTime(2003, 10, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CountryId = new Guid("bc5c0290-49fb-423d-9440-007db6ac1363"),
                            Email = "ah568505@gmail.com",
                            Gender = "Male",
                            RecieveNewsletter = true
                        },
                        new
                        {
                            Id = new Guid("e8bc8b10-cd84-4f5c-8630-50bfd91430b9"),
                            Address = "62 mores st",
                            BirthDate = new DateTime(2000, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CountryId = new Guid("7a536480-94b8-40ea-991d-6cac7ac32a86"),
                            Email = "sa568505@gmail.com",
                            Gender = "Female",
                            RecieveNewsletter = false
                        },
                        new
                        {
                            Id = new Guid("35ed84ce-7a22-4d4d-8764-069c021752b4"),
                            Address = "55 mhamiez st",
                            BirthDate = new DateTime(2001, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CountryId = new Guid("ae6f4b3a-ec46-4e34-99e3-64a0f0d2174b"),
                            Email = "ali568505@gmail.com",
                            Gender = "Male",
                            RecieveNewsletter = true
                        },
                        new
                        {
                            Id = new Guid("bf5eef4d-3422-47cd-90c9-6ed5ad996020"),
                            Address = "77 Porto st",
                            BirthDate = new DateTime(2002, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CountryId = new Guid("bc5c0290-49fb-423d-9440-007db6ac1363"),
                            Email = "jo568505@gmail.com",
                            Gender = "Male",
                            RecieveNewsletter = true
                        },
                        new
                        {
                            Id = new Guid("4ee181a7-2845-4af6-a29a-4fb67a8f90d6"),
                            Address = "48 hendson st",
                            BirthDate = new DateTime(2005, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CountryId = new Guid("8efba64c-38da-4956-8733-dbef6ac860b2"),
                            Email = "ma568505@gmail.com",
                            Gender = "Female",
                            RecieveNewsletter = false
                        },
                        new
                        {
                            Id = new Guid("64d3feeb-4354-4f17-85d2-d6d96aca05b7"),
                            Address = "155 sting st",
                            BirthDate = new DateTime(2011, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CountryId = new Guid("e7d45e4a-be35-4955-9e3a-53e3829df119"),
                            Email = "na568505@gmail.com",
                            Gender = "Female",
                            RecieveNewsletter = true
                        },
                        new
                        {
                            Id = new Guid("75b85283-8384-4c78-9db1-15dd27c9927f"),
                            Address = "120 zodiac st",
                            BirthDate = new DateTime(2010, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CountryId = new Guid("7a536480-94b8-40ea-991d-6cac7ac32a86"),
                            Email = "mo568505@gmail.com",
                            Gender = "Male",
                            RecieveNewsletter = false
                        });
                });

            modelBuilder.Entity("Entities.Person", b =>
                {
                    b.HasOne("Entities.Country", "country")
                        .WithMany("persons")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("country");
                });

            modelBuilder.Entity("Entities.Country", b =>
                {
                    b.Navigation("persons");
                });
#pragma warning restore 612, 618
        }
    }
}
